# -*- coding: utf-8 -*-
"""app.py.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14bzqZeoe47SKYvrnxOzwRataDLnXqpEl
"""

import streamlit as st
import pandas as pd

st.set_page_config(page_title="Simple Dashboard", layout="wide")

st.title("Sales Dashboard (Demo)")

# Tiny sample data
df = pd.DataFrame({
    "Month": ["Jan", "Feb", "Mar", "Apr"],
    "Sales": [120, 150, 90, 210]
})

st.subheader("Data")
st.dataframe(df, width='stretch')

st.subheader("Quick chart")
st.line_chart(df.set_index("Month"))
